### ISSUE TITLE
无法运行服务端 Can not run the server

### ISSUE THREAD

**Issue by KatyushaScarlet** [codehz/mcpeserver#10]
运行环境：ubuntu 16.04 x86-64 WSL
版本：0.5.2
运行命令：
`./mcpeserver download`
`./mcpeserver run`
问题：疑似找不到服务端？
`fork/exec /home/server/bin/server: no such file or directory`
但发现该二进制文件是存在的，手动执行后报错
`-bash: /home/server/bin/server: cannot execute binary file: Exec format error`
![20180708171909](https://user-images.githubusercontent.com/24467495/42418452-44871d0e-82d3-11e8-8938-3f59062d5914.png)

**Comment by KatyushaScarlet** [comment]
补充：该问题在一台Centos7.4环境云主机上也同样出现

**Comment by codehz** [comment]
WSL应该是预期行为，因为WSL没有实现x86
至于centos 7.4云主机，应该日志是不一样的吧。。（只是看起来类似

**Comment by KatyushaScarlet** [comment]
关于readme中，
“./mcpeserver download # download the core binary for minecraft server”
这一步是下载服务端二进制文件，那么apk还是必须的吗？有点疑惑

**Comment by codehz** [comment]
还是必须的，因为主要服务端实现在apk中的so里，然后下载到的二进制是用于加载so的，至于本项目，主要是提供了一个好用的cli，不然就得从MrARM的代码里构建了（显然这会提高很多门槛

**Comment by KatyushaScarlet** [comment]
抱歉，那看来是我误解了流程，没有放入apk文件
希望能够在readme里改进一下，十分感谢

**Comment by codehz** [comment]
明明都写了You must provide a valid minecraft x86 apk。。。
