### ISSUE TITLE
server: relocation error: /lib/libnss_dns.so.2: symbol __resolv_context_get, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

### ISSUE THREAD

**Issue by KatyushaScarlet** [codehz/mcpeserver#11]
服务器环境：
`CentOS Linux release 7.5.1804`
Minecraft PE 版本：
`1.4.4 x86`
apk来源：
`Google Play`
错误信息：
`server: relocation error: /lib/libnss_dns.so.2: symbol __resolv_context_get, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference`
详细日志：
> [root@ltb mcpe]# ./mcpeserver run
> 22:03:48 Trace [Launcher] Loading hybris libraries
> 22:03:48 Trace [Launcher] Loaded OS library libm.so.6
> 22:03:48 Trace [Launcher] Loading Minecraft library
> 22:03:49 Info [Launcher] Loaded Minecraft library
> 22:03:49 Debug [Launcher] Minecraft is at offset 0xf39ce000
> 22:03:49 Info [Launcher] Applying patches
> 22:03:49 Trace [Launcher] Patching - original: 85 83 87 86 131
> 22:03:49 Trace [Launcher] Patching - result: 233 3 251 46 18
> 22:03:49 Info [ModLoader] Loading mods
> 22:03:49 Info [ModLoader] Loaded 0 mods
> 22:03:49 Info [Launcher] Starting server initialization
> 22:03:49 Trace [Launcher] Initializing AppPlatform (vtable)
> 22:03:49 Trace [AppPlatform] Vtable size = 224
> 22:03:49 Trace [Launcher] Initializing AppPlatform (create instance)
> 22:03:49 Trace [Launcher] Initializing AppPlatform (initialize call)
> 22:03:49 Trace [AppPlatform] createDeviceID: 
> 22:03:49 Debug [Launcher] AppPlatform initialized successfully
> 22:03:49 Trace [Launcher] Loading whitelist and operator list
> 22:03:49 Trace [Launcher] Initializing Minecraft API classes
> 22:03:49 Trace [Launcher] Setting up level settings
> 22:03:49 Trace [Launcher] Initializing FilePathManager
> 22:03:49 Trace [AppPlatform] getCurrentStoragePath: /home/mcpe/data/
> 22:03:49 Trace [Launcher] Initializing resource loaders
> 22:03:49 Trace [Launcher] Initializing MinecraftEventing (create instance)
> 22:03:49 Trace [Launcher] Initializing MinecraftEventing (init call)
> 22:03:49 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
> 22:03:49 Trace [Launcher] Initializing ResourcePackManager
> 22:03:49 Trace [Launcher] Initializing PackManifestFactory
> 22:03:49 Trace [Launcher] Initializing SkinPackKeyProvider
> 22:03:49 Trace [Launcher] Initializing StubKeyProvider
> 22:03:49 Trace [Launcher] Initializing PackSourceFactory
> 22:03:49 Trace [Launcher] Initializing ResourcePackRepository
> 22:03:49 Trace [AppPlatform] getInternalStoragePath: /home/mcpe/data/
> 22:03:49 Trace [AppPlatform] getInternalStoragePath: /home/mcpe/data/
> 22:03:49 Trace [AppPlatform] getInternalStoragePath: /home/mcpe/data/
> 22:03:49 Trace [AppPlatform] getInternalStoragePath: /home/mcpe/data/
> 22:03:49 Trace [AppPlatform] getInternalStoragePath: /home/mcpe/data/
> 22:03:49 Trace [AppPlatform] getInternalStoragePath: /home/mcpe/data/
> 22:03:49 Trace [AppPlatform] getInternalStoragePath: /home/mcpe/data/
> 22:03:49 Trace [Launcher] Adding vanilla resource pack
> 22:03:49 Trace [Launcher] Adding world resource packs
> 22:03:49 Trace [Launcher] Initializing Automation::AutomationClient
> 22:03:49 Debug [Launcher] Initializing SaveTransactionManager
> 22:03:49 Debug [Launcher] Initializing ExternalFileLevelStorageSource
> 22:03:49 Debug [Launcher] Initializing ServerInstance
> [MTU] Max MTU Size 1492 bytes
> server: relocation error: /lib/libnss_dns.so.2: symbol __resolv_context_get, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
> mcpe://root@ltb$ 

希望能帮忙看看，十分感谢！

**Comment by codehz** [comment]
是啥系统，alpine吗

**Comment by KatyushaScarlet** [comment]
CentOS7.5，x86_64，腾讯云

**Comment by codehz** [comment]
可能是Centos系统提供的VDSO和我编译时的不一样。。（我建议换一个发行版

**Comment by KatyushaScarlet** [comment]
我自己编译的服务端出现了同样的问题
恩…那我去试试ubuntu

**Comment by KatyushaScarlet** [comment]
成功在ubuntu 16.04上启动了
突然有一个大胆的想法，能否使用arm版apk，在树莓派上开服呢？

**Comment by codehz** [comment]
@KatyushaScarlet 没有这种操作，因为解析so的程序也是架构相关的
