### ISSUE TITLE
Could you show us some API to make modifications?

### ISSUE THREAD

**Issue by YxMingY** [codehz/mcpeserver#12]

**Comment by YxMingY** [comment]
What is the purpose and the usage?

**Comment by codehz** [comment]
Similar to http://www.cydiasubstrate.com/api/c/MSHookFunction/
You have to find the function symbol from libminecraftpe.so
PS: recommended tool: IDA pro 7
This is a example: https://github.com/MCMrARM/mcpelauncher-linux/tree/master/mod_example

**Comment by YxMingY** [comment]
It seems that I need to study more cpp and have to open my server...

**Comment by YxMingY** [comment]
Thanks!
