### ISSUE TITLE
Why not support version 1.5.0.14

### ISSUE THREAD

**Issue by Dmitri233** [codehz/mcpeserver#13]
I can't run the 1.5.0.14 server. When is it supported?

**Comment by codehz** [comment]
Please post the error log.

**Comment by Dmitri233** [comment]
Log:
https://drive.google.com/open?id=1Lhjot8FeyXnbJWjkCwtIsKk_k3NvUF04
photo:
1:https://drive.google.com/open?id=1L8k0XXkBbEtMo4LlzBExMDcffrn9d1st
2:https://drive.google.com/open?id=1Mk0JJoMfZF0PDYfiaj9Ra0hwgWzzuEwu
3:https://drive.google.com/open?id=12bu8yXEGsyty1-pFlp4QnGMDndHl-rGc

**Comment by qwe7002** [comment]
I also encountered this problem, and uuid became a random ID starting with 00000000

**Comment by codehz** [comment]
@Dmitri233 
The log shows that everything is fine. Did you run the `mcpeserver download` after upgrade the version of the minecraft?

**Comment by qwe7002** [comment]
I have already done this, but I still report this problem.

**Comment by codehz** [comment]
Try to run `mcpeserver download` again, the new version of the core has been built(https://hub.docker.com/r/codehz/mcpe-server/builds/bye7jbp6w2xvmyabzc74xk5/)

**Comment by codehz** [comment]
A new version of the core has been built, you can try again with `mcpeserver download`
https://hub.docker.com/r/codehz/mcpe-server/builds/btpm3ncojgfphvykgqebnwv/

**Comment by qwe7002** [comment]
I executed it, but now the situation becomes that the server can't start, and then I prompt this.
![](https://i.loli.net/2018/07/11/5b45dcbc2f1af.png)

**Comment by 894107961** [comment]
I think need to update the mods

**Comment by qwe7002** [comment]
@894107961 I have tried to update the mod,But it didn't work.

**Comment by codehz** [comment]
@qwe7002 I actually not update mods...

**Comment by Dmitri233** [comment]
I am getting an error without installing mods...because I originally wanted to test 1.5

**Comment by Dmitri233** [comment]
If you want to create a new 1.5 server, he will get this error. No old maps or mods installed.

**Comment by greenhat616** [comment]
@codehz 
![image](https://user-images.githubusercontent.com/41122242/42603201-6a72b4d2-859f-11e8-9b80-316705dd238e.png)

Someone was dead, but they can't get revived(via click the button). After disconnect the World, they can't  re-connect any more.

**Comment by codehz** [comment]
@greenhat616 It is very likely that this is a network problem.

**Comment by codehz** [comment]
@Dmitri233 But many people have reported they can actually create 1.5 server, so I think it is wired.

**Comment by Dmitri233** [comment]
He appeared the error I sent above. But I didn't try to join the server. Because I think this failed to open. And there are still many errors? And using: quit will cause a lot of errors. I don't like these errors. At that time the server has no mods.

**Comment by greenhat616** [comment]
@codehz  I'm sure not network problem. With 1.4, It can surely revive

**Comment by codehz** [comment]
@greenhat616 I don't think it can be solved by me, maybe mojang changed some networks related code...

**Comment by codehz** [comment]
@qwe7002  remove all of the mods and try again.
Most of mods are incompatible with 1.5

**Comment by qwe7002** [comment]
@codehz This work seems normal. But when I entered the game for the second time, I found that I returned to my birth point.

**Comment by qwe7002** [comment]
@codehz And I no longer know how much my uuid is.

**Comment by codehz** [comment]
@qwe7002 
I don't know why you will returned to spawn point, it seems a longterm bug since 1.2.x.

**Comment by qwe7002** [comment]
@codehz When I close the game, the reported error is the same as above.
![](https://camo.githubusercontent.com/c896d8a0de882a942971fb17ef50b7e417080ae2/68747470733a2f2f692e6c6f6c692e6e65742f323031382f30372f31312f356234356135373661393835312e6a7067)

**Comment by codehz** [comment]
It is a known crash, and has been fixed in 0.6.x, but it is need more test( and changed directory structure )

**Comment by qwe7002** [comment]
@codehz OK，Thank you for your hard work.Waiting for the official release of 0.6.0, I will test again.

**Comment by codehz** [comment]
In fact the crash after quit is not a big problem, because the world has been saved before crash... so it just spam,
I will close the issue, you can follow #16

**Comment by Dmitri233** [comment]
These small things are handled as well.
