### ISSUE TITLE
运行1.5.0.14服务器时，uuid获取异常并且报错。 When running the 1.5.0.14 server, uuid gets an exception and reports an error.

### ISSUE THREAD

**Issue by qwe7002** [codehz/mcpeserver#14]
运行环境：ubuntu 16.04 x86-64
版本：0.5.2
运行命令：
./mcpeserver run
问题：更新程序版本后，UUID变为000000000开头。且每次登录都不同。服务器运行一段时间后崩溃。以下时崩溃记录：

![](https://i.loli.net/2018/07/11/5b45a576a9851.jpg)

**Comment by Dmitri233** [comment]
看看#13

**Comment by qwe7002** [comment]
>看看#13

@Dmitri233 看起来是同一个问题，我先关了这边
