### ISSUE TITLE
boom~

### ISSUE THREAD

**Issue by 894107961** [codehz/mcpeserver#15]
I use 1.4 world to run on the 1.5.0.14 server,after that the 1.5.0.14 server are begining boom~
The following is my 1.5.0.14 server's record
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Signal 6 received
Backtrace elements: 10
#0 [0x8064cb4]
#1 [0xf77a5400]
#2 [0xf77a5430]
#3 [0x808b847]
#4 [0x8141727]
#5 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x3187f35 [0xf62fff35]
#6 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x3127da9 [0xf629fda9]
#7 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x3127e40 [0xf629fe40]
#8 HYBRIS (null)+-164649046 in libminecraftpe.so+0x31827aa [0xf62fa7aa]
#9 [0x81b569e]
Dumping stack...
#20 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x3187f35 [0xf62fff35]
#21 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x3127da9 [0xf629fda9]
#22 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x3127e40 [0xf629fe40]
#42 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [0xf69e1ff9]
#51 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [0xf69e1ff9]
#83 HYBRIS Player::tickWorld(Tick const&)+0 in libminecraftpe.so+0x21a21b0 [0xf531a1b0]
#84 HYBRIS Player::tickWorld(Tick const&)+0 in libminecraftpe.so+0x21a21b0 [0xf531a1b0]
#91 HYBRIS (null)+14 in libminecraftpe.so+0x31272ce [0xf629f2ce]
#140 HYBRIS (null)+16 in libminecraftpe.so+0x319789e [0xf630f89e]
#232 HYBRIS _ProfilerLiteTimer::~_ProfilerLiteTimer()+24 in libminecraftpe.so+0xdde248 [0xf3f56248]
#259 HYBRIS _ProfilerLiteTimer::~_ProfilerLiteTimer()+24 in libminecraftpe.so+0xdde248 [0xf3f56248]
#368 HYBRIS (null)+187 in libminecraftpe.so+0x3199256 [0xf6311256]
#372 HYBRIS (null)+0 in libminecraftpe.so+0x3198edf [0xf6310edf]
#468 HYBRIS __gnu_cxx::__verbose_terminate_handler()+237 in libminecraftpe.so+0x3187e4d [0xf62ffe4d]
#544 HYBRIS (null)+54 in libminecraftpe.so+0x3126d46 [0xf629ed46]
#549 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [0xf69e1ff9]
#550 HYBRIS (null)+6 in libminecraftpe.so+0x3126d16 [0xf629ed16]
#552 HYBRIS (null)+23 in libminecraftpe.so+0x3126a57 [0xf629ea57]
#556 HYBRIS (null)+8 in libminecraftpe.so+0x3126a48 [0xf629ea48]
#558 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [0xf69e1ff9]
#560 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x3187f35 [0xf62fff35]
#575 HYBRIS __gnu_cxx::__verbose_terminate_handler()+11 in libminecraftpe.so+0x3187d6b [0xf62ffd6b]
#580 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x3127da9 [0xf629fda9]
#584 HYBRIS (null)+62 in libminecraftpe.so+0x3126d9e [0xf629ed9e]
#587 HYBRIS __cxxabiv1::__terminate(void (*)())+11 in libminecraftpe.so+0x3127d9b [0xf629fd9b]
#592 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x3127e40 [0xf629fe40]
#593 HYBRIS __gnu_cxx::__verbose_terminate_handler()+0 in libminecraftpe.so+0x3187d60 [0xf62ffd60]
#595 HYBRIS (null)+9 in libminecraftpe.so+0x31269b9 [0xf629e9b9]
#597 HYBRIS std::terminate()+9 in libminecraftpe.so+0x3127e29 [0xf629fe29]
Signal 6 received 
```

**Comment by codehz** [comment]
Any Mods?

**Comment by 894107961** [comment]
Have no any mods run in to the server

**Comment by codehz** [comment]
Full log?

**Comment by 894107961** [comment]
yes

**Comment by 894107961** [comment]
The 1.4 world can not run in to the 1.5?

**Comment by codehz** [comment]
I don't think it is full log.. you should post the mcpeserver.log

**Comment by qwe7002** [comment]
I think the world of 1.4 can be used for 1.5 because I am using it now.

**Comment by codehz** [comment]
@894107961 it can be upgrade automatically, in theory.

**Comment by 894107961** [comment]
@codehz [0m01:02:05 Trace [1m[Launcher][22m Loading hybris libraries
[0m
[0m01:02:05 Trace [1m[Launcher][22m Loaded OS library libm.so.6
[0m
[0m01:02:05 Trace [1m[Launcher][22m Loading Minecraft library
[0m
[0m01:02:07 Info [1m[Launcher][22m Loaded Minecraft library
[0m
[0m01:02:07 Debug [1m[Launcher][22m Minecraft is at offset 0xf31a7000
[0m
[0m01:02:07 Info [1m[Launcher][22m Applying patches
[0m
[0m01:02:07 Trace [1m[Launcher][22m Patching - original: 85 83 87 86 131
[0m
[0m01:02:07 Trace [1m[Launcher][22m Patching - result: 233 91 149 167 18
[0m
[0m01:02:07 Info [1m[ModLoader][22m Loading mods
[0m
[0m01:02:07 Info [1m[ModLoader][22m Loaded 0 mods
[0m
[0m01:02:07 Info [1m[Launcher][22m Starting server initialization
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing AppPlatform ([4mvtable[24m)
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m Vtable size = 239
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing AppPlatform ([4mcreate instance[24m)
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing AppPlatform ([4minitialize call[24m)
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m createDeviceID: 
[0m
[0m01:02:07 Debug [1m[Launcher][22m AppPlatform initialized successfully
[0m
[0m01:02:07 Trace [1m[Launcher][22m Loading whitelist and operator list
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing Minecraft API classes
[0m
[0m01:02:07 Trace [1m[Launcher][22m Setting up level settings
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing FilePathManager
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getCurrentStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing resource loaders
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing MinecraftEventing ([4mcreate instance[24m)
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing MinecraftEventing ([4minit call[24m)
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getSystemRegion: 0xdeadbeef
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing ResourcePackManager
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing PackManifestFactory
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing SkinPackKeyProvider
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing StubKeyProvider
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing PackSourceFactory
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing ResourcePackRepository
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getInternalStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getInternalStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getInternalStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getInternalStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getInternalStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getInternalStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getInternalStoragePath: /home/s1/data/
[0m
[0m01:02:07 Trace [1m[Launcher][22m Adding vanilla resource pack
[0m
[0m01:02:07 Trace [1m[Launcher][22m Adding world resource packs
[0m
[0m01:02:07 Trace [1m[Launcher][22m Initializing Automation::AutomationClient
[0m
[0m01:02:07 Debug [1m[Launcher][22m Initializing SaveTransactionManager
[0m
[0m01:02:07 Debug [1m[Launcher][22m Initializing ExternalFileLevelStorageSource
[0m
[0m01:02:07 Debug [1m[Launcher][22m Initializing ServerInstance
[0m
[0m[1m[MTU][22m Max MTU Size 1492 bytes
[0m
[0m[1m[IPv6][22m multicast listen on interface 0
[0m
[0msendto failed with code No route to host ([4m113[24m) for char 0 and length 4 for IPv6.
[0m
[0m01:02:07 Trace [1m[Launcher][22m Loading language data
[0m
[0m01:02:07 Info [1m[Launcher][22m Server initialized
[0m
[0m01:02:07 Trace [1m[AppPlatform][22m getAssetFileFullPath: structures/ruin/big_ruin_warm5.nbt
[0m
[0m01:02:08 Debug [1m[Launcher][22m Saving level: world
[0m
[0m[1m[MTU][22m Negotiated MTU Size: 1492 bytes
[0m
[0m01:02:44 Trace [1m[AppPlatform][22m getAssetFileFullPath: structures/ruin/ruin4.nbt
[0m
[0m01:02:45 Debug [1m[Launcher][22m Saving level: world
[0m
[0m[1m[MTU][22m Negotiated MTU Size: 1492 bytes
[0m
[0m01:03:31 Debug [1m[Launcher][22m Saving level: world
[0m
[0m01:03:38 Trace [1m[AppPlatform][22m getAssetFileFullPath: structures/fossils/fossil_spine_04.nbt
[0m
[0m01:03:38 Trace [1m[AppPlatform][22m getAssetFileFullPath: structures/fossils/fossil_spine_04_coal.nbt
[0m
[0m01:04:44 Trace [1m[AppPlatform][22m getAssetFileFullPath: structures/ruin/ruin1_brick.nbt
[0m
[0m01:04:44 Trace [1m[AppPlatform][22m getAssetFileFullPath: structures/ruin/ruin1_cracked.nbt
[0m
[0m01:04:44 Trace [1m[AppPlatform][22m getAssetFileFullPath: structures/ruin/ruin1_mossy.nbt
[0m
[0mterminate called after throwing an instance of 'std::bad_alloc'
[0m
[0m  what([4m[24m):  std::bad_alloc
[0m
[0mSignal 6 received
[0m
[0mBacktrace elements: 10
[0m
[0m#0 [1m[0x8064cb4][22m
[0m
[0m#1 [1m[0xf77d4400][22m
[0m
[0m#2 [1m[0xf77d4430][22m
[0m
[0m#3 [1m[0x808b847][22m
[0m
[0m#4 [1m[0x8141727][22m
[0m
[0m#5 HYBRIS __gnu_cxx::__verbose_terminate_handler([4m[24m)+469 in libminecraftpe.so+0x3187f35 [1m[0xf632ef35][22m
[0m
[0m#6 HYBRIS __cxxabiv1::__terminate([4mvoid ([4m*[24m)([4m[24m)[24m)+25 in libminecraftpe.so+0x3127da9 [1m[0xf62ceda9][22m
[0m
[0m#7 HYBRIS __cxxabiv1::__unexpected([4mvoid ([4m*[24m)([4m[24m)[24m)+0 in libminecraftpe.so+0x3127e40 [1m[0xf62cee40][22m
[0m
[0m#8 HYBRIS ([4mnull[24m)+-164456534 in libminecraftpe.so+0x31827aa [1m[0xf63297aa][22m
[0m
[0m#9 [1m[0x81b569e][22m
[0m
[0mDumping stack...
[0m
[0m#20 HYBRIS __gnu_cxx::__verbose_terminate_handler([4m[24m)+469 in libminecraftpe.so+0x3187f35 [1m[0xf632ef35][22m
[0m
[0m#21 HYBRIS __cxxabiv1::__terminate([4mvoid ([4m*[24m)([4m[24m)[24m)+25 in libminecraftpe.so+0x3127da9 [1m[0xf62ceda9][22m
[0m
[0m#22 HYBRIS __cxxabiv1::__unexpected([4mvoid ([4m*[24m)([4m[24m)[24m)+0 in libminecraftpe.so+0x3127e40 [1m[0xf62cee40][22m
[0m
[0m#42 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [1m[0xf6a10ff9][22m
[0m
[0m#51 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [1m[0xf6a10ff9][22m
[0m
[0m#83 HYBRIS Player::tickWorld([4mTick const&[24m)+0 in libminecraftpe.so+0x21a21b0 [1m[0xf53491b0][22m
[0m
[0m#84 HYBRIS Player::tickWorld([4mTick const&[24m)+0 in libminecraftpe.so+0x21a21b0 [1m[0xf53491b0][22m
[0m
[0m#91 HYBRIS ([4mnull[24m)+14 in libminecraftpe.so+0x31272ce [1m[0xf62ce2ce][22m
[0m
[0m#140 HYBRIS ([4mnull[24m)+16 in libminecraftpe.so+0x319789e [1m[0xf633e89e][22m
[0m
[0m#232 HYBRIS _ProfilerLiteTimer::~_ProfilerLiteTimer([4m[24m)+24 in libminecraftpe.so+0xdde248 [1m[0xf3f85248][22m
[0m
[0m#259 HYBRIS _ProfilerLiteTimer::~_ProfilerLiteTimer([4m[24m)+24 in libminecraftpe.so+0xdde248 [1m[0xf3f85248][22m
[0m
[0m#368 HYBRIS ([4mnull[24m)+187 in libminecraftpe.so+0x3199256 [1m[0xf6340256][22m
[0m
[0m#372 HYBRIS ([4mnull[24m)+0 in libminecraftpe.so+0x3198edf [1m[0xf633fedf][22m
[0m
[0m#468 HYBRIS __gnu_cxx::__verbose_terminate_handler([4m[24m)+237 in libminecraftpe.so+0x3187e4d [1m[0xf632ee4d][22m
[0m
[0m#544 HYBRIS ([4mnull[24m)+54 in libminecraftpe.so+0x3126d46 [1m[0xf62cdd46][22m
[0m
[0m#549 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [1m[0xf6a10ff9][22m
[0m
[0m#550 HYBRIS ([4mnull[24m)+6 in libminecraftpe.so+0x3126d16 [1m[0xf62cdd16][22m
[0m
[0m#552 HYBRIS ([4mnull[24m)+23 in libminecraftpe.so+0x3126a57 [1m[0xf62cda57][22m
[0m
[0m#556 HYBRIS ([4mnull[24m)+8 in libminecraftpe.so+0x3126a48 [1m[0xf62cda48][22m
[0m
[0m#558 HYBRIS typeinfo name for std::bad_alloc+0 in libminecraftpe.so+0x3869ff9 [1m[0xf6a10ff9][22m
[0m
[0m#560 HYBRIS __gnu_cxx::__verbose_terminate_handler([4m[24m)+469 in libminecraftpe.so+0x3187f35 [1m[0xf632ef35][22m
[0m
[0m#575 HYBRIS __gnu_cxx::__verbose_terminate_handler([4m[24m)+11 in libminecraftpe.so+0x3187d6b [1m[0xf632ed6b][22m
[0m
[0m#580 HYBRIS __cxxabiv1::__terminate([4mvoid ([4m*[24m)([4m[24m)[24m)+25 in libminecraftpe.so+0x3127da9 [1m[0xf62ceda9][22m
[0m
[0m#584 HYBRIS ([4mnull[24m)+62 in libminecraftpe.so+0x3126d9e [1m[0xf62cdd9e][22m
[0m
[0m#587 HYBRIS __cxxabiv1::__terminate([4mvoid ([4m*[24m)([4m[24m)[24m)+11 in libminecraftpe.so+0x3127d9b [1m[0xf62ced9b][22m
[0m
[0m#592 HYBRIS __cxxabiv1::__unexpected([4mvoid ([4m*[24m)([4m[24m)[24m)+0 in libminecraftpe.so+0x3127e40 [1m[0xf62cee40][22m
[0m
[0m#593 HYBRIS __gnu_cxx::__verbose_terminate_handler([4m[24m)+0 in libminecraftpe.so+0x3187d60 [1m[0xf632ed60][22m
[0m
[0m#595 HYBRIS ([4mnull[24m)+9 in libminecraftpe.so+0x31269b9 [1m[0xf62cd9b9][22m
[0m
[0m#597 HYBRIS std::terminate([4m[24m)+9 in libminecraftpe.so+0x3127e29 [1m[0xf62cee29][22m
[0m
[0mSignal 6 received
[0m

**Comment by codehz** [comment]
Please upload file instead of paste contents.

**Comment by codehz** [comment]
Or you can upload your world's file to some public accessible cloud storage service, and post the URL

**Comment by 894107961** [comment]
@codehz https://share.weiyun.com/5PcIb9H

**Comment by 894107961** [comment]
@codehz This is log
https://share.weiyun.com/5aJTANq
