### ISSUE TITLE
1.4 world run on the 1.5 server happen error

### ISSUE THREAD

**Issue by 894107961** [codehz/mcpeserver#17]
when I used the command of "/spreadplayers",when the server happen error,and the server was stopping.
![qq 20180712214715](https://user-images.githubusercontent.com/37662946/42637673-5f42a340-861e-11e8-86a8-b8854924b192.png)

**Comment by 894107961** [comment]
I think 1.4 world can not run on the 1.5 server

**Comment by 894107961** [comment]
I hope 1.5 server can compatibility the 1.4 world

**Comment by codehz** [comment]
The error after exited is expected bug, and it will be fixed in next update

**Comment by 894107961** [comment]
@codehz You possible not look carefully of my problem. The /spreadplayers command function is random delivery. I think is loading old world to region block that has not been generated run on the 1.5 server.Loading the new world to generated in the 1.4 world is compatiblilty.

**Comment by 894107961** [comment]
My are not the error after exited is expected bug

**Comment by codehz** [comment]
Try to load the map in client, and then upload to server, it may help to convert the map

**Comment by 894107961** [comment]
@codehz When I running on my computer,my computer as same as server,it succeefully stop!

**Comment by codehz** [comment]
What's means of `succeefully stop`, is client crash?

**Comment by 894107961** [comment]
@codehz No,my computer is stopping.I just restart my computer.

**Comment by 894107961** [comment]
I can join region block that has not been generated,but it is vrey slowly

**Comment by greenhat616** [comment]
Try use Win10 Editon or Pocket Edition(Run On Phone) ?
