### ISSUE TITLE
Where to place server.properties?

### ISSUE THREAD

**Issue by lookas2001** [codehz/mcpeserver#18]
I am using Ubuntu 16.04 and Minecraft Bedrock 1.5.0(Android). The mcpeserver working directory doesn't have a folder named "games" where you said at https://www.v2ex.com/t/423322 to place server.properties in.
Thank you very much.

**Comment by greenhat616** [comment]
You Can make the Dir and make this file, Like:
```
$ cd workDir
$ mkdir games
$ cd games
$ touch server.properties 
$ vim server.properties  # change anything
$ cd ..
$ ./mcpeserver run # generate new world
```

**Comment by codehz** [comment]
Are you using the pre-release version?
It changed location of the config file, and may be changed again.
For now, I suggest to use the v0.5.2

**Comment by lookas2001** [comment]
@codehz Helpful. Thanks!
