### ISSUE TITLE
Unsafe shutdown causes reset of the game save config

### ISSUE THREAD

**Issue by database64128** [codehz/mcpeserver#19]
**Describe the bug**
After an unsafe shutdown of the OS with the server process running and players playing, the game save config was reset and cheat was enabled. Other settings including _emulating distance, show coordinate, etc_ are all reset. We have seen this bug in multiple server VMs.

**To Reproduce**
Start the server in a VM with at least one player playing. Then force stop the VM. Restart the VM and start the server. Now the game save config should be damaged and reset.

**Expected behavior**
The game save config shouldn't be reset or damaged.

**Screenshots**
See this link:
[https://cube64128.cn:666/bug_0.png](https://cube64128.cn:666/bug_0.png)
[https://cube64128.cn:666/bug_1.png](https://cube64128.cn:666/bug_1.png)

**Server (please complete the following information):**
 - OS: CentOS 7 x86_64 1804
 - Version: Latest stable Minecraft Bedrock Edition 1.5

**Additional context**
如果你觉得你更喜欢用中文交流... 当然也是可以的。

**Comment by codehz** [comment]
I think you should backup the world regularly..
The issues is caused by mojang, and I have no idea to solve it.(In fact, the world configuration is completely controlled by mojang's code)

**Comment by codehz** [comment]
@database64128 See https://bugs.mojang.com/browse/MCPE-35324

**Comment by database64128** [comment]
I have encountered that issue for a few players including myself too, but it's not the issue I'm talking about. My problem is, after an unsafe shutdown of the server, the world config is reset to default with cheat on.

**Comment by database64128** [comment]
Also, please add more documentation here on GitHub. The repository is poorly documented and many important details are not mentioned here. I have to find your thread in mcbbs to configure the server, which was written in Chinese and not available for the vast majority of Minecraft community that uses English.
And you may want to introduce your server software to the community on Reddit and other international platforms.

**Comment by codehz** [comment]
The problem also happened in realms server, so I don't think it is my fault. And I don't think it is a good idea to change this behavior before mojang fix it. (it is most likely cause more issues)

**Comment by codehz** [comment]
BTW, more document will be added after 1.0 released
