### ISSUE TITLE
include the chat text from players in the console log

### ISSUE THREAD

**Issue by jason-green-io** [codehz/mcpeserver#20]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to parse the log via a script

**Describe the solution you'd like**
I'd like to see the chat text in the output of the console log like in java edition

**Describe alternatives you've considered**
I've looked in the default log file and the stdout of the process and the chat text is not there

**Additional context**
Is that data even available to the server process in the way it's executed?

**Comment by codehz** [comment]
The chat content can be process via Mods! see https://mcpe.codehz.one/#codehz/chat_log 
(PS: not every mod are compatible with the 1.5, but the chat_log does
Installing mod:
./mcpeserver mods --download codehz/chat_log

**Comment by jason-green-io** [comment]
Perfect!
