### ISSUE TITLE
The mcpeserver v0.6.2 can not to run 1.5.1

### ISSUE THREAD

**Issue by 894107961** [codehz/mcpeserver#22]
The new version of minecraft is 1.5.1,but now mcpeserver can not to run the 1.5.1 server.
![qq 20180721130406](https://user-images.githubusercontent.com/37662946/43032324-96332e50-8ce6-11e8-8055-fe90d432738b.png)

**Comment by 894107961** [comment]
This is log of url https://drive.google.com/file/d/1N9OLyOy0a8piycwblb54Ua3Awda4ev2T/view?usp=drivesdk

**Comment by codehz** [comment]
Duplicated, and the format is incorrect
