### ISSUE TITLE
1.5.1 not working

### ISSUE THREAD

**Issue by KenMizz** [codehz/mcpeserver#23]
**Describe the bug**
1.5.1 not working
**To Reproduce**
Steps to reproduce the behavior.
extract 1.5.1 x86 apk
run server
error
**Expected behavior**
server run successfully
**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 18.10]
 - Version: [e.g. 5.2.0]
OS: Debian 8

**Desktop (please complete the following information):**
 - Device: [e.g. Surface Book 2]
 - OS: [e.g. windows 10 Pro for Workstations 1803]
 - Client Version [e.g. 1.5]
Device Surface pro 4
OS: Windows 10
Client Version: 1.5.1

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS11]
 - Client Version [e.g. 1.5]

**Additional context**

**Comment by Dmitri233** [comment]
See This #22

**Comment by codehz** [comment]
Confirmed, I will fix it soon

**Comment by codehz** [comment]
It should be fixed in 0.6.2
