### ISSUE TITLE
1.5.1.2 can not join the server.

### ISSUE THREAD

**Issue by Dmitri233** [codehz/mcpeserver#24]
**Describe the bug**
"You must authenticate with Xbox Live" when you join the server. I have turned off online mode.

**To Reproduce**
Create a server using x86 apk in 1.5.1.2. Then join the server with 1.5.1.2.

**Expected behavior**
I hope to join the 1.5.1.2 server through 1.5.1.2.

**Screenshots**
Error screenshot: https://drive.google.com/open?id=1k98U801pToLZ-4HOwVW4EgzIqiacsWVY

**Server (please complete the following information):**
 - OS: CentOS 
 - Version: 7 64bit

**Smartphone (please complete the following information):**
 - Device: Redmi 5 Plus
 - OS: Android
 - Client Version : 1.5.1.2

**Additional contex
Log:https://drive.google.com/open?id=1hv6dIyjLHJu_brUuf9yoHkPK5SwW2Yoe

**Comment by codehz** [comment]
If you want login to the server without xbox, you must host the server in LAN.

**Comment by Dmitri233** [comment]
I have already landed on xbox. And I am genuine.

**Comment by qwe7002** [comment]
When I use Version 1.5.1, I often can't log in to the remote server. I just upgraded the game version to 1.5.2, now I feel that the connection success rate has improved a lot.

**Comment by Dmitri233** [comment]
Although 1.5.1 can also join the 1.5.0 server. But I don't have the x86 version of 1.5.0.

**Comment by Dmitri233** [comment]
I am sorry to bother you again. But I can't start the 1.5.0 server with mcpeserver0.6.2. (Map not generated) I have tried my best.
https://drive.google.com/open?id=1PEvaXtux-NpRXWVD7y8RLOfQ5HRJzoLz

**Comment by codehz** [comment]
Yes, 1.5.0 is unsupported, but I don't think your problem is version related

**Comment by Dmitri233** [comment]
1.5.0 server can be used.
https://drive.google.com/open?id=1YE7qLyzpcSSmX0DGpVv86sf7o13jNWDy

**Comment by Dmitri233** [comment]
After I replaced a new ip, the problem "You must pass xbox verification" disappeared. And I am exactly the same configuration. My original ip still prompts this. Can mc be able to ban my ip?

**Comment by codehz** [comment]
@Dmitri233 no, I think it just because the connection issue...
