### ISSUE TITLE
1.5.2 not working

### ISSUE THREAD

**Issue by KenMizz** [codehz/mcpeserver#25]
**Describe the bug**
can't start server on 1.5.2
**To Reproduce**
Steps to reproduce the behavior.
unpack 1.5.2.apk
run the server
error
**Expected behavior**
unpack 1.5.2.apk
successfully run the server
**Screenshots**
![snipaste_2018-07-25_20-23-56](https://user-images.githubusercontent.com/16635884/43200628-b302abea-9048-11e8-92c1-c902c533b5f0.png)

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 18.10]
 - Version: [e.g. 5.2.0]
OS: Debian 8

**Desktop (please complete the following information):**
 - Device: [e.g. Surface Book 2]
 - OS: [e.g. windows 10 Pro for Workstations 1803]
 - Client Version [e.g. 1.5]
Device: Surface pro 4
OS: windows 10 pro
Client Version: 1.5.2

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS11]
 - Client Version [e.g. 1.5]

**Additional context**

**Comment by codehz** [comment]
Try to using 1.5.1.2

**Comment by KenMizz** [comment]
@codehz i don't think mojang release 1.5.1.2, i checked the changelog

**Comment by codehz** [comment]
1.5.1.2
Variant: release/x86; version code: 872050201

**Comment by codehz** [comment]
1.5.1.2
Variant: release/x86; version code: 872050201

**Comment by codehz** [comment]
1.5.1.2
Variant: release/x86; version code: 872050201

**Comment by KenMizz** [comment]
@codehz alright then,thx

**Comment by coolkidsrule101** [comment]
the current version is 1.5.
