### ISSUE TITLE
如何使用WebSocket连接？

### ISSUE THREAD

**Issue by MikaGuraNTK** [codehz/mcpeserver#27]
我做了一个简单执行命令的ws服务器

pe客户端可以正常连接

但是服务器控制台输入wsserver提示
command version mismatch

加上了ws服务器地址就什么都不返回

看见wiki上说了WebSokcet，是可以使用吗？那个token是什么呢？

**Comment by codehz** [comment]
Wsserver在独立服务器中没有被启用，这个是mojang的问题
Wiki上说的是ws服务器，
之前是有的，后面被我去掉了(安全原因)。。。。不过现在你可以使用unix domain socket来连接，具体方式就是用daemon模式运行，然后就可以看到一个.sock文件，连接以后就可以执行命令了

**Comment by MikaGuraNTK** [comment]
@codehz   可是这样不能监听事件啊
默认的wsserver可以监听87种事件
有什么可以监听事件的方法吗

**Comment by codehz** [comment]
@MikaGuraNTK wsserver是Mojang没实现。。。那个命令并不是我控制的

**Comment by codehz** [comment]
@MikaGuraNTK 要监听事件我建议用模组。。。

**Comment by MikaGuraNTK** [comment]
@codehz 请问一下模组使用的是哪种mod呢?pe的addon?

**Comment by codehz** [comment]
参考 codehz/bedrockmod
