### ISSUE TITLE
Server Not Starting/Cannot connect, a bunch of errors

### ISSUE THREAD

**Issue by herohamp** [codehz/mcpeserver#33]
**Describe the bug**
Server Not Starting, a bunch of errors.

**To Reproduce**
Rip Minecraft 1.5.3 APK from Android S8
./mcpeserver download
./mcpeserver unpack -apk XXX.apk
./mcpeserver run 

**Expected behavior**
Server to Start, and me be able to connect to it on the default MCPE port on my VPSes IP

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 18.10]
 - Version: [e.g. 5.2.0]

**Logs*
09:25:53 Trace [Launcher] Loading hybris libraries
09:25:54 Trace [Launcher] Loaded OS library libm.so.6
09:25:54 Trace [Launcher] Loading Minecraft library
09:25:54 Info [Launcher] Loaded Minecraft library
09:25:54 Debug [Launcher] Minecraft is at offset 0xb30ec000
09:25:54 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR9WhitelistRK7OpsListP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsRN9minecraft3api3ApiEibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER17MinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS13_EER9SchedulerEERKSsP9LevelDataPSZ_S11_IFvS1C_EES1H_
09:25:54 Info [Launcher] Applying patches
09:25:54 Trace [Launcher] Patching - original: 85 83 87 86 131
09:25:54 Trace [Launcher] Patching - result: 233 11 159 178 82
09:25:54 Info [ModLoader] Loading mods
09:25:54 Info [ModLoader] Loaded 0 mods
09:25:54 Info [Launcher] Starting server initialization
09:25:54 Trace [Launcher] Initializing AppPlatform (vtable)
09:25:54 Trace [AppPlatform] Vtable size = 238
09:25:54 Trace [Launcher] Initializing AppPlatform (create instance)
09:25:54 Trace [Launcher] Initializing AppPlatform (initialize call)
09:25:54 Trace [AppPlatform] createDeviceID: 
09:25:55 Debug [Launcher] AppPlatform initialized successfully
09:25:55 Trace [Launcher] Loading whitelist and operator list
09:25:55 Trace [Launcher] Initializing Minecraft API classes
09:25:55 Trace [Launcher] Setting up level settings
09:25:55 Trace [Launcher] Initializing FilePathManager
09:25:55 Trace [AppPlatform] getCurrentStoragePath: /root/MCPE/data/
09:25:55 Trace [Launcher] Initializing resource loaders
09:25:55 Trace [Launcher] Initializing MinecraftEventing (create instance)
09:25:55 Trace [Launcher] Initializing MinecraftEventing (init call)
09:25:55 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
09:25:55 Trace [Launcher] Initializing ResourcePackManager
09:25:55 Trace [Launcher] Initializing PackManifestFactory
09:25:55 Trace [Launcher] Initializing SkinPackKeyProvider
09:25:55 Trace [Launcher] Initializing StubKeyProvider
09:25:55 Trace [Launcher] Initializing PackSourceFactory
09:25:55 Trace [Launcher] Initializing ResourcePackRepository
09:25:55 Trace [AppPlatform] getInternalStoragePath: /root/MCPE/data/
09:25:55 Trace [AppPlatform] getInternalStoragePath: /root/MCPE/data/
09:25:55 Trace [AppPlatform] getInternalStoragePath: /root/MCPE/data/
09:25:55 Trace [AppPlatform] getInternalStoragePath: /root/MCPE/data/
09:25:55 Trace [AppPlatform] getInternalStoragePath: /root/MCPE/data/
09:25:55 Trace [AppPlatform] getInternalStoragePath: /root/MCPE/data/
09:25:55 Trace [AppPlatform] getInternalStoragePath: /root/MCPE/data/
09:25:55 Trace [Launcher] Adding vanilla resource pack
09:25:55 Trace [Launcher] Adding world resource packs
09:25:55 Trace [Launcher] Initializing Automation::AutomationClient
09:25:55 Debug [Launcher] Initializing SaveTransactionManager
09:25:55 Debug [Launcher] Initializing ExternalFileLevelStorageSource
09:25:55 Debug [Launcher] Initializing ServerInstance
Signal 11 received  
Backtrace elements: 2
#0 [0x8064cb4]      
#1 [0xb7726500]     
Dumping stack...    
#20 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x31303fc [0xb621c3fc]
#28 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x31303fc [0xb621c3fc]
#34 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x31303e6 [0xb621c3e6]
#68 HYBRIS (null)+12 in libminecraftpe.so+0x2972dcc [0xb5a5edcc]
#100 HYBRIS Core::FileStorageArea::_endTransaction(Core::FileSystemImpl*, bool)+1861 in libminecraftpe.so+0x29349f5 [0xb5a209f5]
#104 HYBRIS Core::FileStorageArea::_endTransaction(Core::FileSystemImpl*, bool)+12 in libminecraftpe.so+0x29342bc [0xb5a202bc]
#108 HYBRIS Core::FileStorageArea::_beginTransaction(Core::FileSystemImpl*, bool)+792 in libminecraftpe.so+0x2934278 [0xb5a20278]
#116 HYBRIS Core::Result::merge(Core::Result&&, Core::Result&&)+15 in libminecraftpe.so+0x293183f [0xb5a1d83f]
#125 HYBRIS vtable for Core::FileSystemImpl+8 in libminecraftpe.so+0x4113720 [0xb71ff720]
#128 HYBRIS Core::FileSystemImpl::FileSystemImpl(Core::FileAccessType, Core::FileStorageArea&, std::shared_ptr<Core::FlatFileManifestTracker>)+216 in libminecraftpe.so+0x2941888 [0xb5a2d888]
#136 HYBRIS Core::FileSystemImpl::_endTransaction()+39 in libminecraftpe.so+0x294e087 [0xb5a3a087]
#141 HYBRIS vtable for Core::FileSystem_generic+8 in libminecraftpe.so+0x4113858 [0xb71ff858]
#148 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x31303fc [0xb621c3fc]
#152 HYBRIS Core::FileSystemImpl::isValidPath(Core::Path)+10 in libminecraftpe.so+0x294774a [0xb5a3374a]
#154 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x31303e6 [0xb621c3e6]
#156 HYBRIS Core::FileSystem_generic::~FileSystem_generic()+35 in libminecraftpe.so+0x295d573 [0xb5a49573]
#160 HYBRIS Core::FileSystem::isValidPath(Core::Path)+336 in libminecraftpe.so+0x29394a0 [0xb5a254a0]
#164 HYBRIS Core::FileSystem::isValidPath(Core::Path)+12 in libminecraftpe.so+0x293935c [0xb5a2535c]
#165 HYBRIS vtable for Core::FileSystem_generic+8 in libminecraftpe.so+0x4113858 [0xb71ff858]
#172 HYBRIS (null)+12 in libminecraftpe.so+0x2972dcc [0xb5a5edcc]
#182 HYBRIS Core::FileSystemImpl::isValidPath(Core::Path)+10 in libminecraftpe.so+0x294774a [0xb5a3374a]
#228 HYBRIS Core::FileStorageArea::_addWriteOperation(bool, unsigned long long)+135 in libminecraftpe.so+0x2934aa7 [0xb5a20aa7]
#489 HYBRIS mce::UUID::EMPTY+0 in libminecraftpe.so+0x43fe854 [0xb74ea854]
#514 HYBRIS mce::UUID::EMPTY+0 in libminecraftpe.so+0x43fe854 [0xb74ea854]
#606 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x31303e6 [0xb621c3e6]
#628 HYBRIS PackIdVersion::operator==(PackIdVersion const&) const+8 in libminecraftpe.so+0x295f3b8 [0xb5a4b3b8]
#640 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x31303fc [0xb621c3fc]
#642 HYBRIS DirectoryPackSource::~DirectoryPackSource()+144 in libminecraftpe.so+0x1e9bb00 [0xb4f87b00]
#646 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x31303e6 [0xb621c3e6]
#648 HYBRIS std::vector<PackIdVersion, std::allocator<PackIdVersion> >::~vector()+321 in libminecraftpe.so+0xe63501 [0xb3f4f501]
#654 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x31303e6 [0xb621c3e6]
#757 HYBRIS mce::UUID::EMPTY+0 in libminecraftpe.so+0x43fe854 [0xb74ea854]
#781 HYBRIS mce::UUID::EMPTY+0 in libminecraftpe.so+0x43fe854 [0xb74ea854]
#808 HYBRIS vtable for SkinPackKeyProvider+8 in libminecraftpe.so+0x40b3f18 [0xb719ff18]
#823 HYBRIS Level::_checkUserStorage()+0 in libminecraftpe.so+0x2465650 [0xb5551650]
#863 HYBRIS vtable for minecraft::api::Api+8 in libminecraftpe.so+0x40aeba4 [0xb719aba4]
#865 HYBRIS vtable for minecraft::api::PlayerInterface+8 in libminecraftpe.so+0x40aebec [0xb719abec]
#866 HYBRIS vtable for minecraft::api::EntityInterface+8 in libminecraftpe.so+0x40aec04 [0xb719ac04]
#867 HYBRIS vtable for minecraft::api::NetworkInterface+8 in libminecraftpe.so+0x40aec14 [0xb719ac14]
#868 HYBRIS vtable for minecraft::api::PlayerInteractionInterface+8 in libminecraftpe.so+0x40aec28 [0xb719ac28]
#906 HYBRIS vtable for ExternalFileLevelStorageSource+8 in libminecraftpe.so+0x41008e4 [0xb71ec8e4]
Signal 6 received

**Comment by codehz** [comment]
It seems you are trying to use 1.5.{1,2,3} in old version of the launcher.
The latest version's launcher is under testing

**Comment by herohamp** [comment]
Oh ok thanks. I switched and it now works. Thanks for making such a great tool
