### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by herohamp** [codehz/mcpeserver#34]
**Is your feature request related to a problem? Please describe.**
There needs to be a way to whitelist users

**Describe the solution you'd like**
The basic whitelist command

**Describe alternatives you've considered**
I havnt found any working alternatives that work in PE

**Comment by codehz** [comment]
If you're using 1.5.0, you can try to download the mod from mcpe.codehz.one and place it in games/mods/, Note: the white list worked with UUID, you can find it when you first login

**Comment by herohamp** [comment]
Thanks
