### ISSUE TITLE
version matched, download skipped

### ISSUE THREAD

**Issue by CrystalRays** [codehz/mcpeserver#35]
**Describe the bug**
when sing ./mcpeserver download
it says version matched, download skipped

**To Reproduce**
./mcpeserver download

**Expected behavior**
do not skipped download 

**Screenshots**
Authorizing...
Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK2pDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXpzeVYwNVpPbFZMUzFJNlJFMUVVanBTU1U5Rk9reEhOa0U2UTFWWVZEcE5SbFZNT2tZelNFVTZOVkF5VlRwTFNqTkdPa05CTmxrNlNrbEVVVEFlRncweE9EQXlNVFF5TXpBMk5EZGFGdzB4T1RBeU1UUXlNekEyTkRkYU1FWXhSREJDQmdOVkJBTVRPMVpCUTFZNk5VNWFNenBNTkZSWk9sQlFTbGc2VWsxQlZEcEdWalpQT2xZMU1sTTZRa2szV2pwU1REVk9PbGhXVDBJNlFsTmFSanBHVTFRMk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMGtyTmgyZWxESnVvYjVERWd5Wi9oZ3l1ZlpxNHo0OXdvNStGRnFRK3VPTGNCMDRyc3N4cnVNdm1aSzJZQ0RSRVRERU9xNW5keEVMMHNaTE51UXRMSlNRdFY1YUhlY2dQVFRkeVJHUTl2aURPWGlqNFBocE40R0N0eFV6YTNKWlNDZC9qbm1YbmtUeDViOElUWXBCZzg2TGNUdmMyRFVUV2tHNy91UThrVjVPNFFxNlZKY05TUWRId1B2Mmp4YWRZa3hBMnhaaWNvRFNFQlpjWGRneUFCRWI2YkRnUzV3QjdtYjRRVXBuM3FXRnRqdCttKzBsdDZOR3hvenNOSFJHd3EwakpqNWtZbWFnWHpEQm5NQ3l5eDFBWFpkMHBNaUlPSjhsaDhRQ09GMStsMkVuV1U1K0thaTZKYVNEOFZJc2VrRzB3YXd4T1dER3U0YzYreE1XYUx3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFdRVU5XT2pWT1dqTTZURFJVV1RwUVVFcFlPbEpOUVZRNlJsWTJUenBXTlRKVE9rSkpOMW82VWt3MVRqcFlWazlDT2tKVFdrWTZSbE5VTmpCR0JnTlZIU01FUHpBOWdEc3lWMDVaT2xWTFMxSTZSRTFFVWpwU1NVOUZPa3hITmtFNlExVllWRHBOUmxWTU9rWXpTRVU2TlZBeVZUcExTak5HT2tOQk5sazZTa2xFVVRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWdZTWF3Si9uMXM0dDlva0VhRjh2aGVkeURzbERObWNyTHNRNldmWTFmRTRDSVFEbzNWazJXcndiSjNmU1dwZEVjT3hNazZ1ZEFwK2c1Nkd6TjlRSGFNeVZ1QT09Il19.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6ImNvZGVoei9tY3BlLXNlcnZlciIsImFjdGlvbnMiOlsicHVsbCJdfV0sImF1ZCI6InJlZ2lzdHJ5LmRvY2tlci5pbyIsImV4cCI6MTUzNDU5NTE4OCwiaWF0IjoxNTM0NTk0ODg4LCJpc3MiOiJhdXRoLmRvY2tlci5pbyIsImp0aSI6Im9HdE9reXc5d3AyN0t3MlptUks1IiwibmJmIjoxNTM0NTk0NTg4LCJzdWIiOiIifQ.a5EKOBdSARRD-qKvzePOe7Pp7EfJ5joYl5iHR1AHmVNph9Fzl_V1-J1FVBziLWyhM3KLeSChH-zgFdD5LP7bxvAbmUgzz39_52oQgO2WOUUro4XtbruaPY5nrs_ZYnNScypMW3dpBalJwArZaoTSurLCJ5LHEcyYMAjp_5eDB84Jqqhx-HZkH40sCfvxXu6tN2MuBjxo4v4yTZ3jufmlJQcQ1um4clY5MR2pAU3frzyl9RkvQ9V55JGsVJHSnAFUDxreeDMvP44uROMx4pm9sHIb8fOf2SPyhgfEMnbtD5C8fvEqdk5UYH-SEQAXFrSgFzVymyVoF4_IW5GeuHicRQ
Fetching...
Blob: sha256:ff4d64e6e5d6b1bdad988db7a1e3e7b4de79004b3f9d8b7ff7ded725a66c1967
Version Matched, Skipped Download.

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 18.10]
 - Version: [e.g. 5.2.0]

**Desktop (please complete the following information):**
 - Device: Tencent Cloud Server
 - OS: debain
 - Client Version [e.g. 1.5]

**Additional context**

**Comment by herohamp** [comment]
You have the latest version downloaded already. Run sha256sum bin.tar.gz to confirm that it matches the sha256 at the bottom of the output

**Comment by codehz** [comment]
Just append the `--force` to download anyway...
And the sha256 is actually matched with the `.version` file :)
I have removed the command in latest commit, and it will be replaced by system package management tool #32

**Comment by CrystalRays** [comment]
@codehz Thanks. @herohamp is right.
Please close this issue. It's my fault.

**Comment by herohamp** [comment]
@codehz strange as when I ran sha256sum on bin.tar.gz. I got the same sha256 as show in the bottom of his output
