### ISSUE TITLE
I can not join in the minecraft server from the outer ,Do I need to set anything in the default.cfg?

### ISSUE THREAD

**Issue by keke1229488344** [codehz/mcpeserver#39]
Sorry to disturb you. I still have some problems in this when I try to join in the server from the outer.
Please let me say something about this situation.
Now,the minecraft server worked. I have stopped the Iptables,and I have mapped the server ports(19132).
I can see the server motd in the lan(when I use WLAN) ,but when I use  mobile network ,I can not see the server motd.
Do I need to set anything in the default.cfg?(Such as server-ip)

PS: This problem is independent of network mapping because I was able to successfully join in the server from the outer when I used your old version!

In Chinese(Sorry,my English may not be very good,you may not understand clearly):
不好意思我英语水平可能不太好，特意写了个中文版本。
（之前有加过你q，就是繁星群的那个。QQ找不到你，现在才想起来应该在github找2333）
我现在情况是局域网可以看得到服务器的motd（不知道为什么访问不了，用PM也是这样的，不知道什么原因），但是用流量（外网）根本看不到motd。我映射方面是没问题的，因为之前你在v2ex那个版本是外网可以用的，archlinux系统里面也关了防火墙什么的。。。所以特地跑来问问是不是需要在配置文件设置IP什么或者允许外网访问之类的，因为我局域网能访问，但是外网访问不了，映射也没问题就很迷。
不好意思啊，麻烦了，谢谢！

**Comment by keke1229488344** [comment]
配置方面没有什么需要设置的吗？

**Comment by codehz** [comment]
@keke1229488344 不同版本也可以显示motd（你可以先试试用原来的版本（

**Comment by keke1229488344** [comment]
emm，用你这个新的，解包以前版本的apk吗？

**Comment by codehz** [comment]
@keke1229488344 不不不，用之前的版本，和之前的apk(

**Comment by keke1229488344** [comment]
那是正常的啊...之前centos试过了就是可以访问的

**Comment by codehz** [comment]
@keke1229488344 所以是玄学（我刚在外网开服测试了

**Comment by keke1229488344** [comment]
还有我现在。。wifi进不去自己内网搭的服务器就很迷（不知道什么情况，pm搭的也不行）

**Comment by keke1229488344** [comment]
那你外网可以进吧，archlinux有没有需要关闭的什么东西才能访问呢？

**Comment by codehz** [comment]
@keke1229488344 可能是XBox认证的锅，你先试试挂个全局VPN，带UDP的那种

**Comment by keke1229488344** [comment]
哇，真的是难受的一批。。还是进不去

**Comment by keke1229488344** [comment]
你这个新的能不能在centos跑啊？

**Comment by codehz** [comment]
@keke1229488344 不能，

**Comment by codehz** [comment]
@keke1229488344 不如试试装个 net-tools 然后执行 netstat -ln

**Comment by keke1229488344** [comment]
好，我试试

**Comment by keke1229488344** [comment]
emmm。
```
[root@FXIT-Arch mcpeserver]#  netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
udp        0      0 0.0.0.0:19111           0.0.0.0:*
udp        0      0 0.0.0.0:68              0.0.0.0:*
udp6       0      0 :::19133                :::*
raw6       0      0 :::58                   :::*                    7
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     SEQPACKET  LISTENING     12549    /run/systemd/coredump
unix  2      [ ACC ]     STREAM     LISTENING     12552    /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     15140    /run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     LISTENING     15142    /run/dhcpcd.unpriv.sock
unix  2      [ ACC ]     STREAM     LISTENING     14920    /run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     18253    /run/screens/S-root/456.1
unix  2      [ ACC ]     STREAM     LISTENING     12678    /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     12942    /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     17369    /run/user/0/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     17376    /run/user/0/p11-kit/pkcs11
unix  2      [ ACC ]     STREAM     LISTENING     17379    /run/user/0/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     17382    /run/user/0/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     17384    /run/user/0/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     17386    /run/user/0/bus
unix  2      [ ACC ]     STREAM     LISTENING     17388    /run/user/0/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     17390    /run/user/0/gnupg/S.gpg-agent
unix  2      [ ACC ]     SEQPACKET  LISTENING     12790    /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     12534    /run/systemd/private
[root@FXIT-Arch mcpeserver]#

```

**Comment by codehz** [comment]
@keke1229488344 看起来你改了端口到19111了

**Comment by keke1229488344** [comment]
没毛病的吧。。

**Comment by codehz** [comment]
@keke1229488344 我觉得还是映射方面的问题。。。我是直接用公网IP跑的

**Comment by keke1229488344** [comment]
我用这台archlinux跑一下你以前的版本试试，看是不是映射问题

**Comment by codehz** [comment]
@keke1229488344 跑PMMP这种就够了（

**Comment by keke1229488344** [comment]
也是。。骚等

**Comment by keke1229488344** [comment]
对的没毛病的。同一台archlinux，跑pm ，流量外网可以看到motd的。

**Comment by codehz** [comment]
@keke1229488344 对比下 netstat -ln

**Comment by keke1229488344** [comment]
```
[root@FXIT-Arch mcpeserver]#  netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
udp        0      0 0.0.0.0:19132           0.0.0.0:*
udp        0      0 0.0.0.0:68              0.0.0.0:*
raw6       0      0 :::58                   :::*                    7
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     SEQPACKET  LISTENING     12549    /run/systemd/coredump
unix  2      [ ACC ]     STREAM     LISTENING     12552    /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     15140    /run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     LISTENING     15142    /run/dhcpcd.unpriv.sock
unix  2      [ ACC ]     STREAM     LISTENING     14920    /run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     18253    /run/screens/S-root/456.1
unix  2      [ ACC ]     STREAM     LISTENING     12678    /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     12942    /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     17369    /run/user/0/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     17376    /run/user/0/p11-kit/pkcs11
unix  2      [ ACC ]     STREAM     LISTENING     17379    /run/user/0/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     17382    /run/user/0/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     17384    /run/user/0/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     17386    /run/user/0/bus
unix  2      [ ACC ]     STREAM     LISTENING     17388    /run/user/0/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     17390    /run/user/0/gnupg/S.gpg-agent
unix  2      [ ACC ]     SEQPACKET  LISTENING     12790    /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     12534    /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     19196    /run/screens/S-root/691.2
[root@FXIT-Arch mcpeserver]#

```

**Comment by keke1229488344** [comment]
但是进不去。。只能是看得到motd

**Comment by codehz** [comment]
@keke1229488344 我比较怀疑是家庭网络问题。。。

**Comment by keke1229488344** [comment]
我也觉得是。。为啥家庭网络不行？我都影射了啊

**Comment by keke1229488344** [comment]
映射了不是和独立ip差不多的效果吗。。

**Comment by codehz** [comment]
@keke1229488344 开服还是商宽比较好

**Comment by keke1229488344** [comment]
emm。。我就搞不懂为啥家庭网不行。。。真的迷

**Comment by keke1229488344** [comment]
好吧谢谢了

**Comment by keke1229488344** [comment]
emm。。可能是dwz和端口映射冲突什么的，目前使用dwz还行。。不过我现在是可以看到motd，但是无法连接至世界.....这是什么情况。。。

**Comment by keke1229488344** [comment]
信号满格绿，但是就是提示连接不上服务器

**Comment by keke1229488344** [comment]
无法连接至世界

**Comment by keke1229488344** [comment]
一直在正在连接外部服务器，然后就提示无法连接至世界

**Comment by codehz** [comment]
@keke1229488344 看起来是客户端的问题，这个得抓包才能知道（

**Comment by keke1229488344** [comment]
要不要qq私发一波端口ip你试试？

**Comment by codehz** [comment]
@keke1229488344 不用了

**Comment by keke1229488344** [comment]
这个貌似是常见的问题，我也不知道是服务端还是客户端问题，因为我在独立ip的腾讯云vps上搭建也有人提示这个问题，出现的概率也是蛮大。部分人会出现部分人不会

**Comment by codehz** [comment]
@keke1229488344 问了几个discord上的用户（海外），他们都表示没有这个问题，所以我估计还是网络相关的（

**Comment by keke1229488344** [comment]
可能是。。我重启手机进腾讯云搭的那个又可以进了。。

**Comment by keke1229488344** [comment]
很迷

**Comment by keke1229488344** [comment]
emmm。。现在连arch上的新版本1.5.3也可以进了。。。就因为重启了手机。。。太迷了，我觉得还是客户端问题。。反正现在天朝玩国际版都是不怎么爽的

**Comment by keke1229488344** [comment]
话说我现在有个问题，就是服务器地图里面死了一次，就有几率变得进不去服务器（一直卡在定位服务器）。这个问题不知道咋回事，但是我想应该可以通过清除玩家数据来解决。就是现在，比如说我想清空某个玩家的数据，应该怎么做呢？（因为你这个不像pm有players文件夹）

**Comment by codehz** [comment]
@keke1229488344 1.5.0的问题，官方已经修复了

**Comment by keke1229488344** [comment]
我用的1.5.1....不是1.5.0啊

**Comment by codehz** [comment]
@keke1229488344 那大概是出生点的问题了，把世界出生点调整到一个正常的位置就好了

**Comment by keke1229488344** [comment]
那假如我要清空某个玩家的信息，不能实现吗？

**Comment by codehz** [comment]
@keke1229488344 不能，不过有第三方存放编辑器

**Comment by keke1229488344** [comment]
mcedit？好像不行。。
第三方存放编辑器？能举个例子不。我去找找
话说这个功能你可以实现吗，还是比较有用的呢。

**Comment by codehz** [comment]
@keke1229488344 是universal minecraft editor，这个功能不好做，官方地图格式天天改

**Comment by keke1229488344** [comment]
还有就是呃。。请问下你之前那个版本的，最高可以支持到哪个版本的MC？

**Comment by codehz** [comment]
@keke1229488344 1.5.0

**Comment by keke1229488344** [comment]
噢噢，谢谢你

**Comment by keke1229488344** [comment]
不好意思，再打扰一下。请问`mcpeserver attach -profile default`命令，可以将要操作的指令与`mcpeserver attach -profile default`合成一条命令执行吗？
因为现在没有rcon，我想实现执行一条命令，然后返回mc的输出内容。使用比如执行一条命令（list），然后返回在线人数。
如果输入mcpeserver attach -profile default，然后再交互式地输入list，就无法读取返回内容了。。。
不知道我表达的是否清晰。。我是想只输入一条命令然后返回mc服务器的内容而不是返回socket

**Comment by codehz** [comment]
@keke1229488344 其实可以不用这个attach也可以执行命令，不过获得结果的话就麻烦一点了。。。我到时候还是做一个子命令来完成这件事情吧。。。
作为参考，你可以使用 `busctl call one.codehz.bedrockserver.default /one/codehz/bedrockserver one.codehz.bedrockserver.core exec s "help" `来发送help命令，然后这个命令返回一个数字编号，但是输出的内容会被发送到one.codehz.bedrockserver.core.exec_result信号（因为是异步执行，可以用 `dbus-monitor --system "type=signal,path=/one/codehz/bedrockserver,interface=one.codehz.bedrockserver.core,member=exec_result"` 来看输出）。。。
所以还是等我加个命令好了

**Comment by keke1229488344** [comment]
要是能实现rcon就非常方便啦！你这个可以是可以。。但是好像是实时输出的。。我貌似还是获取不到结果的。。
你加个命令也行。。那我坐等吧2333

**Comment by codehz** [comment]
@keke1229488344 Rcon是一直有这个计划的。。。因为很多人想要，但是牵涉到的东西比较多，还是用模组做比较靠谱

**Comment by keke1229488344** [comment]
2333....我技术有限，我现在能做到的就是用putty的plink向archlinux发送一条命令，然后获取plink窗口返回的内容仅此而已。。
比如我之前操作那条，就只能获取`[0;34mService Version: [0;35m0.1.5[0m`...
所以说如果是动态的内容貌似是获取不到的（不知道这样表述对不对2333）

**Comment by codehz** [comment]
@keke1229488344 好了，现在pacman -Syu应该能更新到对应版本了（考虑到cdn缓存，你可能需要pacman -Syyuu

**Comment by codehz** [comment]
@keke1229488344 新加的命令是exec用法就是mcpeserver exec help这样（

**Comment by keke1229488344** [comment]
hh！成功了！！可以获取到返回内容了！真的谢谢你！！（抱）

**Comment by keke1229488344** [comment]
可以在其他目录运行吗（例如/home/123）？不一定要在/srv/mcpeserver吧？

**Comment by keke1229488344** [comment]
那算了，不必这样麻烦，谢谢~

**Comment by codehz** [comment]
@keke1229488344 这得问Mojang。。。我没法给他们擦屁股

**Comment by keke1229488344** [comment]
好的吧qwq。。那我得试试你之前说的那啥universal minecraft editor了

**Comment by keke1229488344** [comment]
并不能2333，里面好像只能看到一些位置信息和物品栏之类的。。这不也不是大海捞针。。。没可能根据这两个推啊。。
server_07009dcd-3c15-4d83-b4d0-b0079277248e或者d5f9bf12-8ea4-3e25-a816-4faf81c2ed36应该是xbox的识别码？？可是我登陆xbox.com源码也抓不到什么对的上的号。。。。

**Comment by codehz** [comment]
@keke1229488344 不，这个是玩家UUID，登录的时候可以在服务端内部获得。。。我这有个主意，你可以先下载我的模组包，这里有个工具可以打印登录玩家的id

**Comment by codehz** [comment]
@keke1229488344 模组包： https://54-141378462-gh.circle-artifacts.com/0/data/projects/out/mods.tar.xz

**Comment by keke1229488344** [comment]
好的啊，谢谢！在哪下呢？具体怎么操作呢？

**Comment by codehz** [comment]
@keke1229488344 保存到/srv/mcpeserver/user/mods（注意不要多一层文件夹了
然后写入如下内容到/srv/mcpeserver/user/chai/scripts/init.chai
setWhitelistFilter(fun(UUID uuid) {
Log.info("Whitelist", "UUID: ${uuid.to_string()}");
return true;
});
接下来让玩家尝试连接服务器，就可以在日志里看到UUID了

**Comment by keke1229488344** [comment]
emm。。那ok的。我试试。。话说你这个mod主要是干什么的？

**Comment by codehz** [comment]
@keke1229488344 就是提供了一大堆功能，然后用脚本来配置行为（不写脚本的话应该是不会有任何影响的）

**Comment by keke1229488344** [comment]
好，我试试看，谢谢你

**Comment by codehz** [comment]
记得设定权限，让mcpeserver用户可读（

**Comment by keke1229488344** [comment]
我直接chmod 777好了

**Comment by codehz** [comment]
@keke1229488344 别别别，建议还是chown mcpeserver:mcpeserver /srv/mcpeserver -R 这样如果我代码写出问题，不会搞坏别的东西

**Comment by keke1229488344** [comment]
OK~

**Comment by keke1229488344** [comment]
已经chown mcpeserver:mcpeserver /srv/mcpeserver -R，然而并没有出现/srv/mcpeserver/user/chai文件夹。。。
```
[root@FXIT-Arch mcpeserver]# ls /srv/mcpeserver/user/mods/
chai_base.so     chai_dbus_chat.so  chai_sqlite3.so  chai_transfer.so
chai_chat.so     chai_form.so       chai_test.so     libchai.so
chai_command.so  chai_prop.so       chai_tick.so     libsupport.so
```

**Comment by codehz** [comment]
@keke1229488344 显然你需要自己创建。。。（

**Comment by keke1229488344** [comment]
qwq。。好的吧，我蠢qwq233

**Comment by keke1229488344** [comment]
ok~删掉数据成功，然后就不会出现卡定位了。。只是玩家多的话又得卸档，每个玩家去删，贼麻烦。。。
总之，谢谢你了~

**Comment by codehz** [comment]
@keke1229488344 官方说法是1.5.1解决了这个问题。。。可能是解决了制造问题的那一侧（

**Comment by keke1229488344** [comment]
还有那个。。命令方块失效的问题也是1.5.0的锅吗。。就是命令方块过一会或者重启之类的会自动失效。必须挖掉重新放才行

**Comment by codehz** [comment]
@keke1229488344 我没遇到过，也没听其他用户抱怨过这个。。。所以我也不知道是啥原因

**Comment by codehz** [comment]
@keke1229488344 你先看看是不是命令方块所在的区块被卸载了

**Comment by keke1229488344** [comment]
emm。。我设置了常加载区块。。

**Comment by keke1229488344** [comment]
打扰一下，不知道为何群友普遍反映 新版本项目使用1.5.3比旧版本1.5.0 体验要差一些，按道理来说按这种方式开服的应该不存在这种问题。。问题如图： [图片1](http://pan.fxit.top/index.php?share/file&user=1&sid=aPG5SvUs)  [图片2](http://pan.fxit.top/index.php?share/file&user=1&sid=u2d9agiD)

**Comment by codehz** [comment]
@keke1229488344 这种东西只能说是玄学，另外，客户端掉帧应该和服务端没关系。。。
还有，出现任何bug，请先问候一下Mojang
最后，现在不是1.6.0么

**Comment by keke1229488344** [comment]
2333....看来bugjang确实。。可惜pmmp还没出1.6的啊，所以只能任何这样子233了。等pmmp出了才能更全服的~

**Comment by database64128** [comment]
@keke1229488344 就凭几句随口说的聊天截图就来质疑服务端，这也太不讲道理了吧？还有，PMMP 23小时前就出了1.6，如果你不知道的话。

**Comment by database64128** [comment]
@codehz 请问上面mod包的链接过时了吗？还有能否分享一下1.6正式版的apk？我在Discord上给你发了消息。

**Comment by codehz** [comment]
@database64128 模组已经过时，apk不会分享

**Comment by database64128** [comment]
@keke1229488344 真的对不起，之前语言过激了。我是觉得，你没有在本地网络开服然后连接测试，就不能排除其他因素的干扰。

**Comment by keke1229488344** [comment]
@database64128 2333，没事的，以后有机会可以多交流一下。我目前内测服的服务器就是本地的，让玩家先体验（内测）。1.6目前用着很好呢，也感谢作者的及时更新~

**Comment by keke1229488344** [comment]
@database64128 另外1.6的我有啊，你需要可以找我的。

**Comment by database64128** [comment]
@keke1229488344 谢谢！加你QQ了

**Comment by database64128** [comment]
@codehz 你在 #40 提到mod已经更新支持1.6，能否发下新的链接呢？

**Comment by codehz** [comment]
@database64128 新版模组需要和脚本配合，然后现在正在重构脚本API。。。。如果现在发布的话。。大概又得折腾很多回了（
