### ISSUE TITLE
Update server core to support 1.6.0

### ISSUE THREAD

**Issue by database64128** [codehz/mcpeserver#40]
**Is your feature request related to a problem? Please describe.**
Current server core only supports 1.5.3

**Describe the solution you'd like**
Update server core to support 1.6.0

**Describe alternatives you've considered**
Update server mods to support 1.6.0

**Additional context**

**Comment by codehz** [comment]
done!
Please use `pacman -Syyuu` to force refresh the cache( the cdn will cache some request...)

**Comment by database64128** [comment]
Thanks for the fast update!

**Comment by codehz** [comment]
Mods are also
