### ISSUE TITLE
https://cdn.codehz.one/repo/ubuntu/ error

### ISSUE THREAD

**Issue by KenMizz** [codehz/mcpeserver#42]
**Describe the bug**
https://cdn.codehz.one/repo/ubuntu/ error
**To Reproduce**
Steps to reproduce the behavior.
open the link in the browser
**Expected behavior**
no error
**Screenshots**
![image](https://user-images.githubusercontent.com/16635884/44796694-1ea5b380-abe0-11e8-9aa9-7539e11e2a6d.png)

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 18.10]
 - Version: [e.g. 5.2.0]
Ubuntu 18.10
**Desktop (please complete the following information):**
 - Device: [e.g. Surface Book 2]
 - OS: [e.g. windows 10 Pro for Workstations 1803]
 - Client Version [e.g. 1.5]

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS11]
 - Client Version [e.g. 1.5]

**Additional context**

**Comment by database64128** [comment]
#36

**Comment by database64128** [comment]
The Debian/Ubuntu package was removed and might be added in the future.
