### ISSUE TITLE
建议做成docker镜像

### ISSUE THREAD

**Issue by zxl777** [codehz/mcpeserver#44]
建议做一个docker，部署马上就能运行。
用archlinux做镜像即可，直接就兼容所有系统。

这样也方便做成一键部署，还能避免各种各样的安装兼容性问题。

**Comment by codehz** [comment]
@zxl777 说的好，你来做

**Comment by zxl777** [comment]
没问题，我来做。Discord上联系不到你。

**Comment by zxl777** [comment]
archlinux 的镜像都不带systemd，很麻烦。

**Comment by codehz** [comment]
@zxl777 其实可以试试把system bus作为挂载点（

**Comment by zxl777** [comment]
systemctl reload dbus 这一步就过不去，
Archlinux我没用过，本来希望正确安装一遍，然后做成镜像的。

能不能像以前那样，不用dbus。不用systemd，纯粹一点只用go程序。

置于进程维护，由Docker来负责。

**Comment by codehz** [comment]
@zxl777 reload dbus就不需要了
systemctl其实不是主要依赖，问题在于dbus

**Comment by codehz** [comment]
@zxl777 当然是RPC，由于某些原因，基于文本的方式操作服务端有很多问题

**Comment by zxl777** [comment]
用websocket或者rcon就挺好。

因为要在容器外和容器内的server通讯，用TCP网络通讯最直接。

很难想象再有一个dbus有多麻烦。

**Comment by codehz** [comment]
@zxl777 不不不，这会增加复杂度，而且还有安全隐患，用dbus是安全又简单的方案

**Comment by zxl777** [comment]
我一直用的是rcon，另外有一个go的程序做http到rcon的转发。
其实1.5的实现就蛮好啊，1.5的用到dbus了吗？
1.5在debian上也可以直接运行，
1.6的出现了什么问题？限制了必须用archlinux？

**Comment by codehz** [comment]
@zxl777 主要是静态链接的程序虽然看上去可以用，但是部分发行版上会出现dns解析的问题，导致实际上让那部分服务器的玩家无法登录（其实编译的时候已经有相关警告了），所以最终放弃了静态链接的方案，既然摆脱了静态链接，自然就可以使用一些主流Linux发行版都内置的高级功能了(之前那些功能由于没法静态链接所以不能用)..
其实我就是按照怎么方便怎么来的思路去做的，显然用dbus比自己做websocket服务端要方便

**Comment by zxl777** [comment]
MCMrARM/mcpelauncher-linux 有没有限制非得用 Archlinux？

**Comment by codehz** [comment]
@zxl777 没有，这只是为了我开发方便，你觉得这么做不好的话，可以fork一个（

**Comment by zxl777** [comment]
是的，我还是需要根据我自己的需求fork一个了。
