### ISSUE TITLE
Where do i put mods?

### ISSUE THREAD

**Issue by Unknown4k** [codehz/mcpeserver#46]
i cant find the games/mods folder, im using the ubuntu custom link u sent in other reply

**Comment by codehz** [comment]
@Unknown4k location is user/mods.
TIP:

**Comment by Unknown4k** [comment]
thanks :+1

**Comment by codehz** [comment]
TIPS: my mods is under construction
and it will need write a script to make it actually works.
So, I suggest to use my mods after they have been released...

**Comment by Unknown4k** [comment]
alright, also whats the command to update software ?

**Comment by codehz** [comment]
@Unknown4k For archlinux, just run pacman -Syu
For other distros, waiting for my update tool ( I'm working on it, it will be released in recent )

**Comment by Unknown4k** [comment]
okay ty and really nice work on the software!
