### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by InTheAbsenseOfDemocracyThereIsCommunism** [codehz/mcpeserver#48]
**Describe the bug**
Unable to start server after a self described successful installation.

**To Reproduce**
Install on ubuntu by downloading the precompiled executible, downloading update then extracting an APK, then run mcpeserver run

**Expected behavior**
The server should start and run ideally.

**Screenshots**
![image](https://user-images.githubusercontent.com/30875484/44952738-0df17980-ae3c-11e8-90e8-a51e277b8cc9.png)

**Server (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version: Xenial

**Additional context**
Any help would be appreciated, I am winging this installation since no official guide is available for Ubuntu yet )=

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
Awesome, really appreciate it. Side question, does this server software natively have animal support in game? I would assume less since its using the APK, so I would think it'd have all the features a standard LAN game would have?

**Comment by codehz** [comment]
@InTheAbsenseOfDemocracyThereIsCommunism Yes, it support all the features and BUGS! (So it is not easy to fix some problem, especially something about gameplay)

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
![image](https://user-images.githubusercontent.com/30875484/44952868-f667c000-ae3e-11e8-9ed4-3f0e9114c959.png)
sad

**Comment by codehz** [comment]
@InTheAbsenseOfDemocracyThereIsCommunism Try LD_PRELOAD=./lib ./mcpeserver run

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
Same error, weird.

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
![image](https://user-images.githubusercontent.com/30875484/44952883-61b19200-ae3f-11e8-82f8-05eb13acce6c.png)
Actually there was a bit more, my bad

**Comment by codehz** [comment]
See the edited comments, it should be `LD_LIBRARY_PATH=./lib ./mcpeserver run`

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
![image](https://user-images.githubusercontent.com/30875484/44952914-d08eeb00-ae3f-11e8-9874-09aa566444b9.png)
Different things are happening now

**Comment by codehz** [comment]
Do you put the correct apk and run `./mcpeserver unpack --apk XXX` ? put the output of `ls -alh`

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
![image](https://user-images.githubusercontent.com/30875484/44952930-4430f800-ae40-11e8-9e23-37eadd26af59.png)
I am fairly sure its the correct one 🤔

**Comment by codehz** [comment]
The apk is built for x86 architecture?
Could you find the ./data/libs/libminecraftpe.so ?

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
```
libfmod.so  libminecraftpe.so
pocketmine@vps202862:~/mcpe/data/lib/armeabi-v7a$
```

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
I am not sure, the APK came from a Razer phone, would there be some way to check if it is x86 architecture?

**Comment by codehz** [comment]
no, you have to use the x86 apk and unpack with `./mcpeserver unpack --apk XXX.apk` instead of `unzip`
you can get the x86 apk from internet (like install android emulator and install google play), but I won't tell you more about it, or I may be received the DMCA Takedown :(

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
I will go about the emulator way, since I bought the game and can download it through that. I'll let you know how it goes. Thank you very much for the help so far =)

**Comment by Unknown4k** [comment]
@codehz do you still use your discord?

**Comment by codehz** [comment]
@InTheAbsenseOfDemocracyThereIsCommunism Yes, there are some wip mods for it codehz/bedrockmod
