### ISSUE TITLE
刚刚更新后bedrockserver CPU持续占用100%

### ISSUE THREAD

**Issue by database64128** [codehz/mcpeserver#56]
Arch Linux，之前使用正常，今天更新后，bedrockserver 持续占用100% CPU。
![top](https://user-images.githubusercontent.com/18757988/45069521-9d7a7f00-b0ff-11e8-9b73-2ef7588f95c4.PNG)

attach后可以执行各命令，客户端也可以连接，但是区块加载缓慢（CPU占满的缘故）。

**Comment by codehz** [comment]
没发现这个问题，看看重建地图会不会正常（就是测试时先把原来的地图重命名）

**Comment by database64128** [comment]
我的错😂我开太多虚拟机了，电脑CPU是i5-7400，就4个线程，每个虚拟机都给了2个线程，分配不过来了，加上我地图大、视距开得远，所以体现出来满载😂

**Comment by MyDandan233** [comment]
emmm怎么了

发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: database64128 <notifications@github.com>
发送时间: 2018年9月5日 11:51
收件人: codehz/mcpeserver
抄送: Subscribed
主题: Re: [codehz/mcpeserver] 刚刚更新后bedrockserver CPU持续占用100% (#56)


我的错😂我开太多虚拟机了，电脑CPU是i5-7400，就4个线程，每个虚拟机都给了2个线程，分配不过来了，加上我地图大、视距开得远，所以体现出来满载😂

**Comment by database64128** [comment]
没怎么。。貌似服务器启动以后会以服务器本体所在的位置加载区块，我视距开的56，因为当时虚拟机开多了，实际服务器只得到一个线程，所以加载时间很长。。

Sent from my iPhone

On Sep 8, 2018, at 13:56, MyDandan233 <notifications@github.com<mailto:notifications@github.com>> wrote:

emmm怎么了

发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: database64128 <notifications@github.com<mailto:notifications@github.com>>
发送时间: 2018年9月5日 11:51
收件人: codehz/mcpeserver
抄送: Subscribed
主题: Re: [codehz/mcpeserver] 刚刚更新后bedrockserver CPU持续占用100% (#56)


我的错😂我开太多虚拟机了，电脑CPU是i5-7400，就4个线程，每个虚拟机都给了2个线程，分配不过来了，加上我地图大、视距开得远，所以体现出来满载😂

**Comment by database64128** [comment]
我一直都是视距拉最高，效果好。对我来说，视距10是无法接受的，没法玩。

Sent from my iPhone

On Sep 8, 2018, at 14:20, HongyiMC <notifications@github.com<mailto:notifications@github.com>> wrote:


@database64128<https://github.com/database64128> 为什么要开56视距，10就足够了，56太浪费
