### ISSUE TITLE
Not start in Ubuntu 18.04 or Debian 9

### ISSUE THREAD

**Issue by Shizzlebix** [codehz/mcpeserver#57]
i had download and start your:

getmcpeserver.sh after it was done i had download the 1.6.0.apk for mcpe

now i do that the instruktion say:

sudo ./mcpeserver unpack --apk minecraft-1_6_0.apk

and after i did:

sudo ./mcpeserver run

`I [core] Loading profile: default
W [core] Config file is not exists, creating...
N [core] Loading Bridge...
I [core] Bridge Version: 0.1.7
I [core] Request DBUS Name: one.codehz.bedrockserver.default
I [DBUS] Starting...
mcpe://root@mc$
Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] Signal 11 received

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] Backtrace Count: 8

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #0 ./bin/bedrockserver(+0x3878f) [0x5666378f]

N [core] Loading Bedrock Server...
F [dumper] #1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fae070]
F [dumper] Signal 11 received
F [dumper] Backtrace Count: 8
F [dumper] Dumping stack...
F [dumper] #2 ./bin/bedrockserver(+0x1aeaa) [0x56645eaa]
F [dumper] #3 ./bin/bedrockserver(+0x1b757) [0x56646757]
F [dumper] #4 ./bin/bedrockserver(+0x1b4f7) [0x566464f7]
F [dumper] #5 ./bin/bedrockserver(+0x1a3cd) [0x566453cd]
F [dumper] #6 ./lib/libc.so.6(__libc_start_main+0xf1) [0xf785ab41]
F [dumper] #7 ./bin/bedrockserver(+0x1a40b) [0x5664540b]
F [dumper] #0 ./bin/bedrockserver(+0x3878f) [0x5666378f]
mcpe://root@mc$
Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fae070]

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #2 ./bin/bedrockserver(+0x1aeaa) [0x56645eaa]

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #3 ./bin/bedrockserver(+0x1b757) [0x56646757]

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #4 ./bin/bedrockserver(+0x1b4f7) [0x566464f7]

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #5 ./bin/bedrockserver(+0x1a3cd) [0x566453cd]

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #6 ./lib/libc.so.6(__libc_start_main+0xf1) [0xf785ab41]

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] #7 ./bin/bedrockserver(+0x1a40b) [0x5664540b]

Broadcast message from systemd-journald@mc (Sat 2018-09-08 20:11:30 CEST):

bedrockserver[1189]: [dumper] Dumping stack...

mcpe://root@mc$ ^C
Done.`

it does not work

**Comment by HongyiMC** [comment]
@Shizzlebix Get the x86 apk at
https://drive.google.com/open?id=1--g47RC45G2yUSpqBzgTqtIR7bI28ZYA

**Comment by Shizzlebix** [comment]
i will test and let you know

**Comment by Shizzlebix** [comment]
it will not connect :(
" [Minecraft] NO LOG FILE! - Player connected: 2535445845676368"

searching server (say my client)

**Comment by alovegit** [comment]
@Shizzlebix I had the same issue with older CPUs. I now run my Linux in a VM which works.
