### ISSUE TITLE
mcpeserver无法下载核心提示Error:  runtime error: index out of range怎么办

### ISSUE THREAD

**Issue by ghost** [codehz/mcpeserver#58]
**Describe the bug**
输入./mcpeserver download后提示Error:  runtime error: index out of range

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 18.10]
 - Version: [e.g. 5.2.0]

**Desktop (please complete the following information):**
 - Device: [e.g. Surface Book 2]
 - OS: [e.g. windows 10 Pro for Workstations 1803]
 - Client Version [e.g. 1.5]

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS11]
 - Client Version [e.g. 1.5]

**Additional context**

**Comment by codehz** [comment]
please use the latest build 
installation script: https://gist.github.com/codehz/610bdeba96fcec16e6339abae7208e7d

**Comment by ghost** [comment]
不行啊

**Comment by codehz** [comment]
please read the readme! do not use the github release
