### ISSUE TITLE
Default map, changing the seed

### ISSUE THREAD

**Issue by Guilhem30** [codehz/mcpeserver#6]
Nice tool, finally a way to run a proper mcpe server!
But the default map has me spawn in a cave filled with water. Had to transfer a map from my phone to make the server playable. Is there a way to change the seed directly on the server side ?

**Comment by codehz** [comment]
See https://github.com/MCMrARM/mcpelauncher-linux/wiki/Dedicated-Server

You can edit the server.properties to change the seed.(configuration file in ./games/server.properties)

Tip: you have to remove old map after change the seed.

**Comment by Guilhem30** [comment]
I think i tried that and it made the server crash yesterday.
Will try again later and report back.
The default seed doesn't seem to be random though.
I removed the default map and it generated the same one again.

**Comment by codehz** [comment]
Yes, the default seed is 0 currently.
But I'm going to refactoring the code, and it will be solved

**Comment by Guilhem30** [comment]
Nice. Would it be possible to implement Xbox Live support if the server is launched with some microsoft account logins?
This would allow to join with consoles too.

**Comment by codehz** [comment]
@Guilhem30 but they say it will support to add server recently...

**Comment by Guilhem30** [comment]
They are going to add realm support but I doubt they will add custom servers too.
Anyway I would understand if it's too much work to implement, I have looked at the code and it doesn't look easy for me.

**Comment by codehz** [comment]
@Guilhem30 There are many differences between dedicated server and normal multiplayer world, for example, the dedicated server cannot have host player...

**Comment by Guilhem30** [comment]
Okay, I didn't realize the program actually launch a real dedicated server. Since we are using the apk version I thought it was just creating a normal multiplayer world but using a linux server without gui.
